Caliel test
MadMofin/jest-learning pull request #4
Opened 2023-04-22 00:03 UTC by CalielTW

2023-04-22 00:35 UTC, CalielTW commented
Se resolvio un error de merge en el apartado de calculator, con las funciones de setData y handleSelect, al igual que algunos errores al momento de generar tests visuales en los ultimos 2 pull requests

2023-04-22 00:44 UTC, liazcortez commented on src/components/Calculator.jsx
falta renderizar data.error

2023-04-22 00:50 UTC, liazcortez commented on src/components/__tests__/Calculator.test.tsx
no era necesario cambiar los test de calculator.tests.tsx

2023-04-22 00:51 UTC, liazcortez requested changes
falta renderizar el data.error

2023-04-25 00:57 UTC, liazcortez requested changes

2023-04-25 00:57 UTC, liazcortez commented on src/components/__tests__/Calculator.test.tsx
falta terminar tests

2023-04-27 00:30 UTC, CalielTW commented
![imagen_2023-04-26_183014151](https://user-images.githubusercontent.com/119454264/234730207-5c0b6374-2916-42b8-bb2a-5fefe8df600c.png)

Esta seria la vista del calculador

2023-06-07 15:07 UTC, closed without merging