feat operation results history
MadMofin/jest-learning pull request #5
Opened 2023-04-22 00:07 UTC by liazcortez

>**21/042023**

**Updates**

- History of the last 10 operations was implemented, saving itself in an array and if it has more than 10 elements, it eliminates the last element of the array to save the most recent element

2023-04-25 00:24 UTC, CalielTW commented on src/App.css
> +
Seria mejor crear un archivo nuevo como history.css para este agregado

2023-04-25 00:28 UTC, CalielTW requested changes
Añadir tests de los archivos agregados

2023-04-25 00:28 UTC, CalielTW commented on src/App.tsx
> +// import History from "./components/History";
Si no se utilizara borrarlo directamente

2023-04-25 00:28 UTC, CalielTW commented on src/components/History.jsx
Podrias añadir algun preview de como se ve implementado?

2023-04-25 00:28 UTC, CalielTW commented on src/components/Calculator.jsx
> +    let newResults = results || [];
Cambiar newResults a una constante

2023-04-28 09:39 UTC, liazcortez commented on src/App.css
> +
listo

2023-12-27 17:07 UTC, closed without merging